In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import seaborn as sns; sns.set(style="ticks", color_codes=True)

In [2]:
features=pd.read_csv('features.csv')

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
stores = pd.read_csv('stores.csv')
sample_submission=pd.read_csv('sampleSubmission.csv')
features=pd.read_csv('features.csv')

In [3]:
dataset = pd.read_csv("train.csv",sep=',', header=0)
dataset = dataset.merge(stores, how='left')
dataset=dataset.merge(features,how='left')

In [4]:
testdataset= pd.read_csv("test.csv",sep=',', header=0)
testdataset=testdataset.merge(stores,how='left')
testdataset=testdataset.merge(features,how='left')

In [5]:
testdataset['Weekly_Sales']=0

In [6]:
testdataset['Type_A']=pd.get_dummies(testdataset['Type'])['A']
testdataset['Type_B']=pd.get_dummies(testdataset['Type'])['B']
testdataset['Type_C']=pd.get_dummies(testdataset['Type'])['C']
testdataset=testdataset.drop(['Type'],axis=1)

In [18]:
Nan_percent = dataset.isnull().sum()*100/len(dataset)
Nan_percent

Store           0.0
Dept            0.0
Date            0.0
Weekly_Sales    0.0
IsHoliday       0.0
Size            0.0
Temperature     0.0
Fuel_Price      0.0
MarkDown1       0.0
MarkDown2       0.0
MarkDown3       0.0
MarkDown4       0.0
MarkDown5       0.0
CPI             0.0
Unemployment    0.0
Type_A          0.0
Type_B          0.0
Type_C          0.0
dtype: float64

In [19]:
Nan_data_test = testdataset.isnull().sum()*100/len(testdataset)
Nan_data_test

Store            0.00000
Dept             0.00000
Date             0.00000
IsHoliday        0.00000
Size             0.00000
Temperature      0.00000
Fuel_Price       0.00000
MarkDown1        0.00000
MarkDown2        0.00000
MarkDown3        0.00000
MarkDown4        0.00000
MarkDown5        0.00000
CPI             33.16589
Unemployment    33.16589
Weekly_Sales     0.00000
Type_A           0.00000
Type_B           0.00000
Type_C           0.00000
dtype: float64

In [9]:
dataset['Type_A']=pd.get_dummies(dataset['Type'])['A']
dataset['Type_B']=pd.get_dummies(dataset['Type'])['B']
dataset['Type_C']=pd.get_dummies(dataset['Type'])['C']
dataset=dataset.drop(['Type'],axis=1)

In [16]:
#print(dataset['MarkDown1'].describe())
#print(dataset['MarkDown2'].describe())
#print(dataset['MarkDown3'].describe())
#print(dataset['MarkDown4'].describe())
#print(dataset['MarkDown5'].describe())
print(testdataset['MarkDown1'].describe())
print(testdataset['MarkDown2'].describe())
print(testdataset['MarkDown3'].describe())
print(testdataset['MarkDown4'].describe())
print(testdataset['MarkDown5'].describe())

count    114915.000000
mean       7689.216439
std       10698.760716
min       -2781.450000
25%        1966.460000
50%        4842.290000
75%        9439.140000
max      103184.980000
Name: MarkDown1, dtype: float64
count    86437.000000
mean      3734.051729
std       8323.495014
min        -35.740000
25%        180.350000
50%        742.590000
75%       2735.670000
max      71074.170000
Name: MarkDown2, dtype: float64
count    105235.000000
mean       2403.088666
std       13767.939313
min        -179.260000
25%          15.100000
50%          78.260000
75%         272.580000
max      149483.310000
Name: MarkDown3, dtype: float64
count    102176.000000
mean       3356.219071
std        7570.501545
min           0.220000
25%         155.460000
50%         840.940000
75%        3096.920000
max       65344.640000
Name: MarkDown4, dtype: float64
count    115064.000000
mean       3922.681189
std       19445.150745
min        -185.170000
25%        1309.300000
50%        2390.430000
75%        4227.270000
max      771448.100000
Name: MarkDown5, dtype: float64

In [17]:
dataset['MarkDown1']=dataset['MarkDown1'].fillna(7246)
dataset['MarkDown2']=dataset['MarkDown2'].fillna(3334)
dataset['MarkDown3']=dataset['MarkDown3'].fillna(1439)
dataset['MarkDown4']=dataset['MarkDown4'].fillna(3383)
dataset['MarkDown5']=dataset['MarkDown5'].fillna(4628)
testdataset['MarkDown1']=testdataset['MarkDown1'].fillna(7689)
testdataset['MarkDown2']=testdataset['MarkDown2'].fillna(3734)
testdataset['MarkDown3']=testdataset['MarkDown3'].fillna(2403)
testdataset['MarkDown4']=testdataset['MarkDown4'].fillna(3356)
testdataset['MarkDown5']=testdataset['MarkDown5'].fillna(3922)

In [182]:
#dataset[['MarkDown1','MarkDown2','MarkDown3','MarkDown4', 'MarkDown5']] = dataset[['MarkDown1','MarkDown2','MarkDown3','MarkDown4','MarkDown5']].fillna(0)

In [183]:
#testdataset[['MarkDown1','MarkDown2','MarkDown3','MarkDown4', 'MarkDown5']] = testdataset[['MarkDown1','MarkDown2','MarkDown3','MarkDown4','MarkDown5']].fillna(0)

In [184]:
Markdown1_train=dataset[(dataset['MarkDown1']!=0)]
Markdown1_train=Markdown1_train.drop(["MarkDown2","MarkDown3","MarkDown4","MarkDown5"],axis=1)
Markdown1_test=dataset[(dataset['MarkDown1']==0)]
Markdown1_test=Markdown1_test.drop(["MarkDown2","MarkDown3","MarkDown4","MarkDown5"],axis=1)
Markdown2_train=dataset[(dataset['MarkDown2']!=0)]
Markdown2_train=Markdown2_train.drop(["MarkDown1","MarkDown3","MarkDown4","MarkDown5"],axis=1)
Markdown2_test=dataset[(dataset['MarkDown2']==0)]
Markdown2_test=Markdown2_test.drop(["MarkDown1","MarkDown3","MarkDown4","MarkDown5"],axis=1)
Markdown3_train=dataset[(dataset['MarkDown3']!=0)]
Markdown3_train=Markdown3_train.drop(["MarkDown2","MarkDown1","MarkDown4","MarkDown5"],axis=1)
Markdown3_test=dataset[(dataset['MarkDown3']==0)]
Markdown3_test=Markdown3_test.drop(["MarkDown2","MarkDown1","MarkDown4","MarkDown5"],axis=1)
Markdown4_train=dataset[(dataset['MarkDown4']!=0)]
Markdown4_train=Markdown4_train.drop(["MarkDown2","MarkDown3","MarkDown1","MarkDown5"],axis=1)
Markdown4_test=dataset[(dataset['MarkDown4']==0)]
Markdown4_test=Markdown4_test.drop(["MarkDown2","MarkDown3","MarkDown1","MarkDown5"],axis=1)
Markdown5_train=dataset[(dataset['MarkDown5']!=0)]
Markdown5_train=Markdown5_train.drop(["MarkDown2","MarkDown3","MarkDown4","MarkDown1"],axis=1)
Markdown5_test=dataset[(dataset['MarkDown5']==0)]
Markdown5_test=Markdown5_test.drop(["MarkDown2","MarkDown3","MarkDown4","MarkDown1"],axis=1)

In [20]:
testdataset['CPI']=testdataset['CPI'].fillna(176)# 176 is the mean of all CPI values
testdataset['Unemployment']=testdataset['Unemployment'].fillna(6.868) # 6.86 is the mean of all Unemployment rates.

In [23]:
dataset['Month']= pd.to_datetime(dataset['Date']).dt.month

In [73]:
testdataset['Month']=pd.to_datetime(testdataset['Date']).dt.month

In [28]:
X=dataset.drop(["Date","Weekly_Sales"],axis=1)
y=dataset['Weekly_Sales']
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)
lm=LinearRegression()
lm.fit(X_train,y_train)
predictions=lm.predict(X_test)

In [27]:
X_train

,Store,Dept,IsHoliday,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type_A,Type_B,Type_C,Month
129684,14,12,True,200898,70.87,2.699,7246.00,3334.00,1439.00,3383.00,4628.00,182.598178,8.743,1,0,0,9
136020,14,79,False,200898,41.18,3.513,4605.80,21593.85,636.54,727.57,4054.79,189.326096,8.424,1,0,0,1
322819,34,17,False,158114,65.41,3.620,2716.10,3334.00,6.03,1648.80,3539.71,131.075667,8.839,1,0,0,10
333929,35,25,False,103681,70.31,2.755,7246.00,3334.00,1439.00,3383.00,4628.00,136.557015,8.861,0,1,0,8
162560,17,38,False,93188,39.94,3.755,5593.69,112.20,1439.00,134.13,748.23,131.193097,5.527,0,1,0,10
33892,4,32,False,205863,40.31,3.290,1346.06,3740.12,46.16,445.47,2451.89,130.314452,4.607,1,0,0,1
277335,29,2,True,93638,36.28,3.402,2168.59,17155.07,47.22,332.96,1792.92,136.643258,9.357,0,1,0,12
417975,45,52,False,118221,78.47,3.760,7246.00,3334.00,1439.00,3383.00,4628.00,186.139981,8.625,0,1,0,7
54629,6,45,False,202505,53.74,2.732,7246.00,3334.00,1439.00,3383.00,4628.00,212.533737,7.259,1,0,0,3
175674,18,83,False,120653,27.40,3.139,7246.00,3334.00,1439.00,3383.00,4628.00,132.680452,9.331,0,1,0,12
284228,29,72,False,93638,39.42,3.065,7246.00,3334.00,1439.00,3383.00,4628.00,132.756667,10.524,0,1,0,12
74534,8,44,False,155078,86.05,3.638,7246.00,3334.00,1439.00,3383.00,4628.00,219.007525,6.425,1,0,0,8
283168,29,54,False,93638,65.01,2.830,7246.00,3334.00,1439.00,3383.00,4628.00,132.435742,10.160,0,1,0,6
91080,10,27,False,126512,83.49,2.935,7246.00,3334.00,1439.00,3383.00,4628.00,126.114000,9.524,0,1,0,6
81145,9,19,False,125833,63.96,3.372,7246.00,3334.00,1439.00,3383.00,4628.00,221.315956,6.054,0,1,0,10
321615,34,8,False,158114,80.23,3.617,7246.00,3334.00,1439.00,3383.00,4628.00,129.201581,10.641,1,0,0,8
100279,11,19,False,207499,76.97,3.285,7246.00,3334.00,1439.00,3383.00,4628.00,220.429901,7.197,1,0,0,10
141695,15,27,False,123737,62.53,2.837,7246.00,3334.00,1439.00,3383.00,4628.00,132.761933,8.099,0,1,0,9
375250,40,33,False,155083,67.47,2.810,7246.00,3334.00,1439.00,3383.00,4628.00,132.630000,5.326,1,0,0,8
63398,7,33,False,70713,22.20,3.031,56917.70,1839.82,4.53,16241.73,2414.97,196.872892,8.256,0,1,0,2
386697,41,46,False,196321,40.23,2.788,7246.00,3334.00,1439.00,3383.00,4628.00,189.490412,7.363,1,0,0,5
402087,43,60,False,41062,88.49,3.637,7246.00,3334.00,1439.00,3383.00,4628.00,206.856024,10.581,0,0,1,6
341185,36,8,False,39910,48.74,2.995,7246.00,3334.00,1439.00,3383.00,4628.00,210.968241,8.395,1,0,0,1
22149,3,12,True,37392,68.00,3.236,41.74,10.47,37612.74,3383.00,135.16,221.901118,7.197,0,1,0,11
221225,23,32,False,114533,56.80,4.056,7503.68,200.82,10.50,1993.04,6412.69,138.653400,4.156,0,1,0,9
277948,29,6,False,93638,54.18,4.029,2264.29,3334.00,6.80,829.39,675.12,138.911700,9.151,0,1,0,10
235010,24,80,False,203819,42.30,3.627,8915.25,3334.00,209.71,2399.76,23368.58,136.503067,8.454,1,0,0,12
331005,35,2,False,103681,36.96,3.567,2798.44,2928.52,1.46,446.00,9008.25,140.912402,8.744,0,1,0,1
381308,41,3,False,196321,32.70,2.973,7246.00,3334.00,1439.00,3383.00,4628.00,191.573192,7.241,1,0,0,1
10154,1,98,False,151315,66.57,3.372,7246.00,3334.00,1439.00,3383.00,4628.00,217.676679,7.866,1,0,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28488,3,87,False,37392,69.47,3.488,7246.00,3334.00,1439.00,3383.00,4628.00,217.723523,7.551,0,1,0,3
140844,15,21,False,123737,39.63,3.065,7246.00,3334.00,1439.00,3383.00,4628.00,132.978323,8.067,0,1,0,11
251298,26,32,False,152513,65.54,3.840,2430.95,16.00,5.54,829.70,3038.77,138.185710,7.405,1,0,0,8
280635,29,27,False,93638,35.34,3.263,7246.00,3334.00,1439.00,3383.00,4628.00,133.370143,10.256,0,1,0,2
346995,37,4,False,39910,59.15,3.459,7246.00,3334.00,1439.00,3383.00,4628.00,212.861131,8.395,0,0,1,3
231325,24,33,False,203819,42.20,3.049,7246.00,3334.00,1439.00,3383.00,4628.00,132.924581,8.275,1,0,0,11
315763,33,14,False,39690,76.80,3.145,7246.00,3334.00,1439.00,3383.00,4628.00,126.208548,9.849,1,0,0,5
125064,13,60,False,219622,49.96,2.831,7246.00,3334.00,1439.00,3383.00,4628.00,126.491290,7.795,1,0,0,11
91642,10,31,False,126512,65.29,3.004,7246.00,3334.00,1439.00,3383.00,4628.00,126.601903,9.524,0,1,0,4
340591,36,3,False,39910,82.30,2.615,7246.00,3334.00,1439.00,3383.00,4628.00,210.213567,8.464,1,0,0,6
32817,4,25,False,205863,74.44,2.621,7246.00,3334.00,1439.00,3383.00,4628.00,126.089290,7.372,1,0,0,8
391208,42,2,False,39690,52.33,3.034,7246.00,3334.00,1439.00,3383.00,4628.00,126.604286,9.765,0,0,1,3
348637,37,16,True,39910,84.19,3.730,319.93,3334.00,251.31,354.73,2145.98,221.118114,6.623,0,0,1,9
121861,13,31,False,219622,79.18,3.624,21327.53,50.44,88.44,9444.60,3872.19,130.885355,5.765,1,0,0,8
412782,45,6,False,118221,75.09,3.867,23641.30,6.00,92.93,6988.31,3992.13,191.461281,8.684,0,1,0,8
340700,36,3,False,39910,78.15,3.245,769.50,3334.00,0.01,3383.00,1530.69,220.606344,6.623,1,0,0,7
323317,34,22,False,158114,42.65,2.654,7246.00,3334.00,1439.00,3383.00,4628.00,126.578286,9.521,1,0,0,3
250792,26,29,False,152513,16.30,3.281,7246.00,3334.00,1439.00,3383.00,4628.00,133.492143,7.907,1,0,0,2
35391,4,45,False,205863,50.93,3.461,7246.00,3334.00,1439.00,3383.00,4628.00,128.399500,6.510,1,0,0,3
349828,37,38,False,39910,66.34,2.633,7246.00,3334.00,1439.00,3383.00,4628.00,210.514440,8.476,0,0,1,10
153128,16,40,False,57197,28.64,2.684,7246.00,3334.00,1439.00,3383.00,4628.00,189.737207,7.039,0,1,0,3
148429,16,3,False,57197,65.43,3.741,3644.68,37.20,63.90,611.78,5520.95,197.655186,6.169,0,1,0,6
228745,24,14,False,203819,71.99,3.006,7246.00,3334.00,1439.00,3383.00,4628.00,132.364839,8.211,1,0,0,6
413679,45,13,False,118221,78.37,2.715,7246.00,3334.00,1439.00,3383.00,4628.00,182.604292,8.743,0,1,0,9
55293,6,54,False,202505,64.94,2.719,7246.00,3334.00,1439.00,3383.00,4628.00,212.332281,7.092,1,0,0,4
311895,32,80,False,203007,67.17,2.800,7246.00,3334.00,1439.00,3383.00,4628.00,190.468829,9.017,1,0,0,9
136767,14,85,False,200898,72.62,3.834,6647.88,34.56,255.31,6931.80,9414.10,191.344887,8.684,1,0,0,8
204614,21,67,False,140167,78.91,3.355,7246.00,3334.00,1439.00,3383.00,4628.00,216.362033,7.852,0,1,0,9
214539,22,74,False,119557,46.03,2.834,7246.00,3334.00,1439.00,3383.00,4628.00,135.668225,8.283,0,1,0,3
176991,18,97,False,120653,73.12,3.784,7246.00,3334.00,1439.00,3383.00,4628.00,135.628333,8.890,0,1,0,7

In [203]:
predictions=np.where(predictions<=0,0, predictions)

In [74]:
y_m1test=testdataset.drop(["Date","Weekly_Sales"],axis=1)

In [65]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, rf_predictions)

1712.6661766017507

In [60]:
r2_score(y_test, knn_predictions)

0.27233543183343956

In [45]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.feature_selection import RFE
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import KFold

In [51]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
train_scaled=scaler.fit_transform(X_train)
test_scaled=scaler.transform(X_test)

C:\Users\Sinan\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype bool, uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Sinan\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype bool, uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Sinan\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype bool, uint8, int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.

In [57]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()
model.fit(train_scaled,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [58]:
knn_predictions=model.predict(test_scaled)

In [63]:
modelrf=RandomForestRegressor()
modelrf.fit(train_scaled,y_train)

C:\Users\Sinan\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [64]:
rf_predictions=modelrf.predict(test_scaled)

In [79]:
scaled_data=scaler.fit_transform(y_m1test)

C:\Users\Sinan\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype bool, uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Sinan\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype bool, uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [80]:
results=modelrf.predict(scaled_data)

In [85]:
sample_submission['Weekly_Sales']=results

In [91]:
sample_submission

                      Id  Weekly_Sales
0         1_1_2012-11-02     19457.773
1         1_1_2012-11-09     22007.085
2         1_1_2012-11-16     19891.613
3         1_1_2012-11-23     21420.876
4         1_1_2012-11-30     24901.331
5         1_1_2012-12-07     29954.078
6         1_1_2012-12-14     39731.857
7         1_1_2012-12-21     38398.561
8         1_1_2012-12-28     23565.930
9         1_1_2013-01-04     44190.434
10        1_1_2013-01-11     38856.317
11        1_1_2013-01-18     23399.277
12        1_1_2013-01-25     28107.365
13        1_1_2013-02-01     23933.175
14        1_1_2013-02-08     32352.617
15        1_1_2013-02-15     22218.840
16        1_1_2013-02-22     20886.542
17        1_1_2013-03-01     29315.246
18        1_1_2013-03-08     18098.786
19        1_1_2013-03-15     16302.240
20        1_1_2013-03-22     68456.222
21        1_1_2013-03-29     28107.920
22        1_1_2013-04-05     19531.499
23        1_1_2013-04-12     18438.498
24        1_1_2013-04-19     17305.141
25        1_1_2013-04-26     19191.481
26        1_1_2013-05-03     19109.662
27        1_1_2013-05-10     19365.982
28        1_1_2013-05-17     19237.455
29        1_1_2013-05-24     18026.903
...                  ...           ...
115034  45_98_2013-01-04       519.623
115035  45_98_2013-01-11       786.185
115036  45_98_2013-01-18       703.626
115037  45_98_2013-01-25       367.465
115038  45_98_2013-02-01       773.376
115039  45_98_2013-02-08       732.589
115040  45_98_2013-02-15       721.457
115041  45_98_2013-02-22       720.187
115042  45_98_2013-03-01       689.539
115043  45_98_2013-03-08       732.837
115044  45_98_2013-03-15       708.846
115045  45_98_2013-03-22       751.154
115046  45_98_2013-03-29       702.428
115047  45_98_2013-04-05       716.347
115048  45_98_2013-04-12       697.100
115049  45_98_2013-04-19       689.228
115050  45_98_2013-04-26       731.472
115051  45_98_2013-05-03       153.808
115052  45_98_2013-05-10       217.109
115053  45_98_2013-05-17       369.359
115054  45_98_2013-05-24       363.137
115055  45_98_2013-05-31       340.433
115056  45_98_2013-06-07       295.334
115057  45_98_2013-06-14       301.969
115058  45_98_2013-06-21       301.969
115059  45_98_2013-06-28       234.943
115060  45_98_2013-07-05       295.334
115061  45_98_2013-07-12       295.334
115062  45_98_2013-07-19       252.715
115063  45_98_2013-07-26       310.022

[115064 rows x 2 columns]

In [92]:
sample_submission.to_csv('../walmart_submission.csv',index=False)

In [84]:
y_m1test

,Store,Dept,IsHoliday,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type_A,Type_B,Type_C,Month
0,1,1,False,151315,55.32,3.386,6766.44,5147.70,50.82,3639.90,2737.42,223.462779,6.573,1,0,0,11
1,1,1,False,151315,61.24,3.314,11421.32,3370.89,40.28,4646.79,6154.16,223.481307,6.573,1,0,0,11
2,1,1,False,151315,52.92,3.252,9696.28,292.10,103.78,1133.15,6612.69,223.512911,6.573,1,0,0,11
3,1,1,True,151315,56.23,3.211,883.59,4.17,74910.32,209.91,303.32,223.561947,6.573,1,0,0,11
4,1,1,False,151315,52.34,3.207,2460.03,3734.00,3838.35,150.57,6966.34,223.610984,6.573,1,0,0,11
5,1,1,False,151315,64.12,3.198,6343.16,3734.00,270.00,2928.90,10147.90,223.660021,6.573,1,0,0,12
6,1,1,False,151315,48.89,3.168,3504.83,3734.00,73.26,1636.80,2779.60,223.719277,6.573,1,0,0,12
7,1,1,False,151315,56.02,3.098,8231.71,3734.00,274.00,358.15,2834.02,223.839845,6.573,1,0,0,12
8,1,1,True,151315,44.79,3.108,12659.55,37101.13,174.78,74.46,1208.86,223.960414,6.573,1,0,0,12
9,1,1,False,151315,41.73,3.161,1214.08,25366.33,15.01,72.36,3940.02,224.080983,6.525,1,0,0,1
10,1,1,False,151315,50.32,3.243,6520.24,16134.60,12.17,774.55,4001.25,224.201552,6.525,1,0,0,1
11,1,1,False,151315,42.92,3.237,3772.69,3559.46,3.88,246.62,1900.40,224.235813,6.525,1,0,0,1
12,1,1,False,151315,53.37,3.227,965.89,1097.91,0.10,225.36,1831.88,224.235552,6.525,1,0,0,1
13,1,1,False,151315,56.46,3.244,9290.91,1359.90,265.00,20657.82,972.61,224.235290,6.525,1,0,0,2
14,1,1,True,151315,56.67,3.417,32355.16,729.80,280.89,20426.61,4671.78,224.235029,6.525,1,0,0,2
15,1,1,False,151315,49.66,3.475,72937.29,6665.52,47.21,13014.67,6310.18,224.276053,6.525,1,0,0,2
16,1,1,False,151315,50.25,3.597,20107.75,3163.89,42.20,15657.30,5812.86,224.420289,6.525,1,0,0,2
17,1,1,False,151315,48.01,3.711,10610.74,261.46,2.80,25.54,2747.59,224.564526,6.525,1,0,0,3
18,1,1,False,151315,50.81,3.658,5000.58,290.46,78.77,606.15,3697.11,224.708763,6.525,1,0,0,3
19,1,1,False,151315,55.33,3.622,3808.13,3734.00,15.65,2616.60,1909.17,224.835681,6.525,1,0,0,3
20,1,1,False,151315,63.42,3.611,12553.98,3734.00,495.10,6787.75,2545.66,224.919300,6.525,1,0,0,3
21,1,1,False,151315,51.00,3.606,13067.46,3734.00,384.90,122.93,3903.80,225.002920,6.525,1,0,0,3
22,1,1,False,151315,58.59,3.583,12872.34,5687.86,485.97,478.04,5092.33,225.086540,6.314,1,0,0,4
23,1,1,False,151315,62.72,3.529,3672.43,932.58,52.86,949.07,2836.64,225.170160,6.314,1,0,0,4
24,1,1,False,151315,67.10,3.451,3530.36,3.95,107.50,458.76,2062.05,225.170160,6.314,1,0,0,4
25,1,1,False,151315,59.23,3.417,2387.72,3734.00,98.34,516.28,1421.63,225.170160,6.314,1,0,0,4
26,1,1,False,151315,66.66,3.386,2298.63,2.00,129.90,55.46,1301.04,176.000000,6.868,1,0,0,5
27,1,1,False,151315,63.90,3.392,4624.61,83.88,42.38,1618.31,8144.90,176.000000,6.868,1,0,0,5
28,1,1,False,151315,69.53,3.454,16170.50,92.00,8.32,4127.24,6206.97,176.000000,6.868,1,0,0,5
29,1,1,False,151315,77.19,3.494,7959.89,178.00,1621.47,3152.57,2938.70,176.000000,6.868,1,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115034,45,98,False,118221,32.87,3.592,1341.33,30325.14,8.93,35.85,3682.17,192.659622,8.625,0,1,0,1
115035,45,98,False,118221,38.78,3.611,3877.36,15559.85,3.81,152.18,2403.14,192.759980,8.625,0,1,0,1
115036,45,98,False,118221,41.45,3.605,14746.10,4071.06,4.02,483.58,1467.78,192.809507,8.625,0,1,0,1
115037,45,98,False,118221,26.49,3.583,3130.28,1362.10,0.20,332.68,1361.74,192.838701,8.625,0,1,0,1
115038,45,98,False,118221,34.92,3.615,14508.96,1092.53,827.90,26424.02,700.93,192.867895,8.625,0,1,0,2
115039,45,98,True,118221,28.99,3.753,53311.88,531.33,78.26,24823.94,3233.44,192.897089,8.625,0,1,0,2
115040,45,98,False,118221,35.87,3.814,9362.02,2017.68,0.36,5012.39,6411.71,192.943471,8.625,0,1,0,2
115041,45,98,False,118221,31.48,3.859,10781.51,2735.67,23.38,1516.76,3061.21,193.032822,8.625,0,1,0,2
115042,45,98,False,118221,39.72,3.890,6614.32,147.82,5.60,27.55,1668.95,193.122173,8.625,0,1,0,3
115043,45,98,False,118221,36.13,3.860,16382.54,88.67,34.62,3096.92,3486.91,193.211524,8.625,0,1,0,3
115044,45,98,False,118221,42.81,3.834,9867.03,3734.00,11.08,912.87,1360.36,193.296277,8.625,0,1,0,3
115045,45,98,False,118221,36.55,3.800,11923.74,3734.00,308.00,1764.47,1647.31,193.369533,8.625,0,1,0,3
115046,45,98,False,118221,40.68,3.784,5444.00,3734.00,350.84,53.90,1722.11,193.442790,8.625,0,1,0,3
115047,45,98,False,118221,43.94,3.763,16427.83,5341.41,182.59,1523.83,1743.09,193.516047,8.335,0,1,0,4
115048,45,98,False,118221,57.39,3.724,8760.15,1713.11,21.08,1302.31,1380.74,193.589304,8.335,0,1,0,4
115049,45,98,False,118221,56.27,3.676,1399.81,39.89,44.38,60.83,1445.05,193.589304,8.335,0,1,0,4
115050,45,98,False,118221,50.64,3.615,1260.65,3734.00,57.52,40.51,2476.18,193.589304,8.335,0,1,0,4
115051,45,98,False,118221,56.07,3.592,8345.40,6.00,92.96,3580.32,2242.24,176.000000,6.868,0,1,0,5
115052,45,98,False,118221,58.86,3.583,4689.18,440.82,53.09,375.22,5738.20,176.000000,6.868,0,1,0,5
115053,45,98,False,118221,60.59,3.614,4515.35,667.88,6.12,522.70,2541.62,176.000000,6.868,0,1,0,5
115054,45,98,False,118221,67.11,3.627,3249.34,481.82,58.48,1183.23,1309.30,176.000000,6.868,0,1,0,5
115055,45,98,False,118221,65.88,3.646,6474.49,411.38,77.06,9.38,4227.27,176.000000,6.868,0,1,0,5
115056,45,98,False,118221,70.71,3.633,9977.82,744.29,80.00,4825.71,3597.34,176.000000,6.868,0,1,0,6
115057,45,98,False,118221,70.01,3.632,2471.44,517.87,348.54,2612.33,3459.39,176.000000,6.868,0,1,0,6
115058,45,98,False,118221,70.13,3.626,4989.34,385.31,178.56,2463.42,3117.94,176.000000,6.868,0,1,0,6
115059,45,98,False,118221,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,176.000000,6.868,0,1,0,6
115060,45,98,False,118221,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,176.000000,6.868,0,1,0,7
115061,45,98,False,118221,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,176.000000,6.868,0,1,0,7
115062,45,98,False,118221,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,176.000000,6.868,0,1,0,7
115063,45,98,False,118221,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,176.000000,6.868,0,1,0,7

In [ ]:
y_predict = model.predict(X_test)

In [ ]:
dataset.iloc[:,2]

In [25]:
pd.DataFrame(predictions,y_test)

                         0
Weekly_Sales
9214.04       28275.688033
2681.04       15846.663043
14683.34      19674.516316
45.00          3349.029974
120557.54     22588.397953
5658.50       18535.668606
5221.03        8824.540355
5421.14       14270.341895
3816.56       10570.573131
49.26          6920.283339
41008.01      17553.093025
19798.48      11179.792109
28.92         16902.540979
2705.79       16326.804933
2363.66       10391.471354
113.57        11681.734743
50197.97      24739.765369
12396.98      15709.363398
1933.16       16917.091138
26049.53      18070.366317
30.00         23558.739205
32.48         18364.575189
59.08         20418.278973
2.00           5985.653620
3852.40        9178.035099
76.34          7177.097840
7212.24       20330.651307
43265.29      28829.524233
4826.13        4240.432493
175.13        12843.457677
...                    ...
6964.62        6086.722686
18929.70      19727.350597
9194.86        9173.379672
13004.52      20859.802299
772.29        19196.551491
21802.77       7926.869492
2114.38       14827.921227
11673.81       4612.824634
35288.96      18536.113376
12030.76      12005.434453
24.48         12565.186978
236.55        -1939.756234
813.94        15461.426103
88.00         24763.513639
5961.00       13310.057996
4773.03       13549.996640
2666.87       14258.061964
2371.75       16316.571166
11137.95        376.020988
22638.40      18567.957982
3305.15       15902.428551
22632.51      28007.070323
44366.29      12771.011298
17052.54      21710.980604
83.00         19428.747968
3187.04       29607.254754
5756.62       14292.262291
23170.55      26718.756235
406.21        -1267.807456
49617.89      11677.375961

[126471 rows x 1 columns]

In [207]:
predictions_MD1=lm.predict(y_m1test)

In [209]:
X=Markdown2_train.drop(["Date","Weekly_Sales","MarkDown2"],axis=1)
y=Markdown2_train['MarkDown2']
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)
lm2=LinearRegression()
lm2.fit(X_train,y_train)
predictions_MD2=lm2.predict(y_m1test)

In [211]:
X=Markdown3_train.drop(["Date","Weekly_Sales","MarkDown3"],axis=1)
y=Markdown3_train['MarkDown3']
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)
lm3=LinearRegression()
lm3.fit(X_train,y_train)
predictions_MD3=lm3.predict(y_m1test)

In [212]:
X=Markdown4_train.drop(["Date","Weekly_Sales","MarkDown4"],axis=1)
y=Markdown4_train['MarkDown4']
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)
lm4=LinearRegression()
lm4.fit(X_train,y_train)
predictions_MD4=lm4.predict(y_m1test)

In [213]:
X=Markdown5_train.drop(["Date","Weekly_Sales","MarkDown5"],axis=1)
y=Markdown5_train['MarkDown5']
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)
lm5=LinearRegression()
lm5.fit(X_train,y_train)
predictions_MD5=lm5.predict(y_m1test)

In [236]:
testdataset['cl3'].describe()

count    115064.000000
mean       1419.516505
std        4072.211228
min       -2606.096946
25%         -69.741933
50%         401.617292
75%         901.022185
max       17117.912880
Name: cl3, dtype: float64

In [235]:
testdataset['MarkDown3'].describe()

count    115064.000000
mean       2197.811964
std       13183.888087
min        -179.260000
25%           7.770000
50%          60.000000
75%         244.200000
max      149483.310000
Name: MarkDown3, dtype: float64

In [155]:
testdataset

,Store,Dept,Date,IsHoliday,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Weekly_Sales,Type_A,Type_B,Type_C
0,1,1,2012-11-02,False,151315,55.32,3.386,6766.44,5147.70,50.82,3639.90,2737.42,223.462779,6.573,0,1,0,0
1,1,1,2012-11-09,False,151315,61.24,3.314,11421.32,3370.89,40.28,4646.79,6154.16,223.481307,6.573,0,1,0,0
2,1,1,2012-11-16,False,151315,52.92,3.252,9696.28,292.10,103.78,1133.15,6612.69,223.512911,6.573,0,1,0,0
3,1,1,2012-11-23,True,151315,56.23,3.211,883.59,4.17,74910.32,209.91,303.32,223.561947,6.573,0,1,0,0
4,1,1,2012-11-30,False,151315,52.34,3.207,2460.03,0.00,3838.35,150.57,6966.34,223.610984,6.573,0,1,0,0
5,1,1,2012-12-07,False,151315,64.12,3.198,6343.16,0.00,270.00,2928.90,10147.90,223.660021,6.573,0,1,0,0
6,1,1,2012-12-14,False,151315,48.89,3.168,3504.83,0.00,73.26,1636.80,2779.60,223.719277,6.573,0,1,0,0
7,1,1,2012-12-21,False,151315,56.02,3.098,8231.71,0.00,274.00,358.15,2834.02,223.839845,6.573,0,1,0,0
8,1,1,2012-12-28,True,151315,44.79,3.108,12659.55,37101.13,174.78,74.46,1208.86,223.960414,6.573,0,1,0,0
9,1,1,2013-01-04,False,151315,41.73,3.161,1214.08,25366.33,15.01,72.36,3940.02,224.080983,6.525,0,1,0,0
10,1,1,2013-01-11,False,151315,50.32,3.243,6520.24,16134.60,12.17,774.55,4001.25,224.201552,6.525,0,1,0,0
11,1,1,2013-01-18,False,151315,42.92,3.237,3772.69,3559.46,3.88,246.62,1900.40,224.235813,6.525,0,1,0,0
12,1,1,2013-01-25,False,151315,53.37,3.227,965.89,1097.91,0.10,225.36,1831.88,224.235552,6.525,0,1,0,0
13,1,1,2013-02-01,False,151315,56.46,3.244,9290.91,1359.90,265.00,20657.82,972.61,224.235290,6.525,0,1,0,0
14,1,1,2013-02-08,True,151315,56.67,3.417,32355.16,729.80,280.89,20426.61,4671.78,224.235029,6.525,0,1,0,0
15,1,1,2013-02-15,False,151315,49.66,3.475,72937.29,6665.52,47.21,13014.67,6310.18,224.276053,6.525,0,1,0,0
16,1,1,2013-02-22,False,151315,50.25,3.597,20107.75,3163.89,42.20,15657.30,5812.86,224.420289,6.525,0,1,0,0
17,1,1,2013-03-01,False,151315,48.01,3.711,10610.74,261.46,2.80,25.54,2747.59,224.564526,6.525,0,1,0,0
18,1,1,2013-03-08,False,151315,50.81,3.658,5000.58,290.46,78.77,606.15,3697.11,224.708763,6.525,0,1,0,0
19,1,1,2013-03-15,False,151315,55.33,3.622,3808.13,0.00,15.65,2616.60,1909.17,224.835681,6.525,0,1,0,0
20,1,1,2013-03-22,False,151315,63.42,3.611,12553.98,0.00,495.10,6787.75,2545.66,224.919300,6.525,0,1,0,0
21,1,1,2013-03-29,False,151315,51.00,3.606,13067.46,0.00,384.90,122.93,3903.80,225.002920,6.525,0,1,0,0
22,1,1,2013-04-05,False,151315,58.59,3.583,12872.34,5687.86,485.97,478.04,5092.33,225.086540,6.314,0,1,0,0
23,1,1,2013-04-12,False,151315,62.72,3.529,3672.43,932.58,52.86,949.07,2836.64,225.170160,6.314,0,1,0,0
24,1,1,2013-04-19,False,151315,67.10,3.451,3530.36,3.95,107.50,458.76,2062.05,225.170160,6.314,0,1,0,0
25,1,1,2013-04-26,False,151315,59.23,3.417,2387.72,0.00,98.34,516.28,1421.63,225.170160,6.314,0,1,0,0
26,1,1,2013-05-03,False,151315,66.66,3.386,2298.63,2.00,129.90,55.46,1301.04,176.000000,6.868,0,1,0,0
27,1,1,2013-05-10,False,151315,63.90,3.392,4624.61,83.88,42.38,1618.31,8144.90,176.000000,6.868,0,1,0,0
28,1,1,2013-05-17,False,151315,69.53,3.454,16170.50,92.00,8.32,4127.24,6206.97,176.000000,6.868,0,1,0,0
29,1,1,2013-05-24,False,151315,77.19,3.494,7959.89,178.00,1621.47,3152.57,2938.70,176.000000,6.868,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115034,45,98,2013-01-04,False,118221,32.87,3.592,1341.33,30325.14,8.93,35.85,3682.17,192.659622,8.625,0,0,1,0
115035,45,98,2013-01-11,False,118221,38.78,3.611,3877.36,15559.85,3.81,152.18,2403.14,192.759980,8.625,0,0,1,0
115036,45,98,2013-01-18,False,118221,41.45,3.605,14746.10,4071.06,4.02,483.58,1467.78,192.809507,8.625,0,0,1,0
115037,45,98,2013-01-25,False,118221,26.49,3.583,3130.28,1362.10,0.20,332.68,1361.74,192.838701,8.625,0,0,1,0
115038,45,98,2013-02-01,False,118221,34.92,3.615,14508.96,1092.53,827.90,26424.02,700.93,192.867895,8.625,0,0,1,0
115039,45,98,2013-02-08,True,118221,28.99,3.753,53311.88,531.33,78.26,24823.94,3233.44,192.897089,8.625,0,0,1,0
115040,45,98,2013-02-15,False,118221,35.87,3.814,9362.02,2017.68,0.36,5012.39,6411.71,192.943471,8.625,0,0,1,0
115041,45,98,2013-02-22,False,118221,31.48,3.859,10781.51,2735.67,23.38,1516.76,3061.21,193.032822,8.625,0,0,1,0
115042,45,98,2013-03-01,False,118221,39.72,3.890,6614.32,147.82,5.60,27.55,1668.95,193.122173,8.625,0,0,1,0
115043,45,98,2013-03-08,False,118221,36.13,3.860,16382.54,88.67,34.62,3096.92,3486.91,193.211524,8.625,0,0,1,0
115044,45,98,2013-03-15,False,118221,42.81,3.834,9867.03,0.00,11.08,912.87,1360.36,193.296277,8.625,0,0,1,0
115045,45,98,2013-03-22,False,118221,36.55,3.800,11923.74,0.00,308.00,1764.47,1647.31,193.369533,8.625,0,0,1,0
115046,45,98,2013-03-29,False,118221,40.68,3.784,5444.00,0.00,350.84,53.90,1722.11,193.442790,8.625,0,0,1,0
115047,45,98,2013-04-05,False,118221,43.94,3.763,16427.83,5341.41,182.59,1523.83,1743.09,193.516047,8.335,0,0,1,0
115048,45,98,2013-04-12,False,118221,57.39,3.724,8760.15,1713.11,21.08,1302.31,1380.74,193.589304,8.335,0,0,1,0
115049,45,98,2013-04-19,False,118221,56.27,3.676,1399.81,39.89,44.38,60.83,1445.05,193.589304,8.335,0,0,1,0
115050,45,98,2013-04-26,False,118221,50.64,3.615,1260.65,0.00,57.52,40.51,2476.18,193.589304,8.335,0,0,1,0
115051,45,98,2013-05-03,False,118221,56.07,3.592,8345.40,6.00,92.96,3580.32,2242.24,176.000000,6.868,0,0,1,0
115052,45,98,2013-05-10,False,118221,58.86,3.583,4689.18,440.82,53.09,375.22,5738.20,176.000000,6.868,0,0,1,0
115053,45,98,2013-05-17,False,118221,60.59,3.614,4515.35,667.88,6.12,522.70,2541.62,176.000000,6.868,0,0,1,0
115054,45,98,2013-05-24,False,118221,67.11,3.627,3249.34,481.82,58.48,1183.23,1309.30,176.000000,6.868,0,0,1,0
115055,45,98,2013-05-31,False,118221,65.88,3.646,6474.49,411.38,77.06,9.38,4227.27,176.000000,6.868,0,0,1,0
115056,45,98,2013-06-07,False,118221,70.71,3.633,9977.82,744.29,80.00,4825.71,3597.34,176.000000,6.868,0,0,1,0
115057,45,98,2013-06-14,False,118221,70.01,3.632,2471.44,517.87,348.54,2612.33,3459.39,176.000000,6.868,0,0,1,0
115058,45,98,2013-06-21,False,118221,70.13,3.626,4989.34,385.31,178.56,2463.42,3117.94,176.000000,6.868,0,0,1,0
115059,45,98,2013-06-28,False,118221,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,176.000000,6.868,0,0,1,0
115060,45,98,2013-07-05,False,118221,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,176.000000,6.868,0,0,1,0
115061,45,98,2013-07-12,False,118221,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,176.000000,6.868,0,0,1,0
115062,45,98,2013-07-19,False,118221,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,176.000000,6.868,0,0,1,0
115063,45,98,2013-07-26,False,118221,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,176.000000,6.868,0,0,1,0

In [221]:
testdataset['MarkDown2'][4]==0

True

In [169]:
for i in range(0,115064):
    if testdataset['MarkDown1'][i]==0.0:
        testdataset['MarkDown1'][i]==predictions_MD1[i]
    if testdataset['MarkDown2'][i]==0.0:
        testdataset['MarkDown2'][i]==predictions_MD2[i]
    if testdataset['MarkDown3'][i]==0.0:
        testdataset['MarkDown3'][i]==predictions_MD3[i]
    if testdataset['MarkDown4'][i]==0.0:
        testdataset['MarkDown4'][i]==predictions_MD4[i]
    if testdataset['MarkDown5'][i]==0.0:
        testdataset['MarkDown5'][i]==predictions_MD5[i]

In [237]:
TT=testdataset.drop(["MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5"],axis=1)

In [238]:
TT

,Store,Dept,Date,IsHoliday,Size,Temperature,Fuel_Price,CPI,Unemployment,Weekly_Sales,Type_A,Type_B,Type_C,cl1,cl2,cl3,cl4,cl5
0,1,1,2012-11-02,False,151315,55.32,3.386,223.462779,6.573,0,1,0,0,6730.864162,3556.203113,288.531761,2895.048423,5245.614632
1,1,1,2012-11-09,False,151315,61.24,3.314,223.481307,6.573,0,1,0,0,6673.018940,3109.156083,390.405129,2920.499719,5585.114909
2,1,1,2012-11-16,False,151315,52.92,3.252,223.512911,6.573,0,1,0,0,6649.159154,4549.166247,566.425807,3162.193933,5676.482029
3,1,1,2012-11-23,True,151315,56.23,3.211,223.561947,6.573,0,1,0,0,5567.929414,13410.902839,15233.262569,2847.920373,4227.241032
4,1,1,2012-11-30,False,151315,52.34,3.207,223.610984,6.573,0,1,0,0,6620.956493,4851.395935,657.539160,3247.507169,5824.785485
5,1,1,2012-12-07,False,151315,64.12,3.198,223.660021,6.573,0,1,0,0,6592.133956,3293.591060,597.095894,3069.347043,6032.751557
6,1,1,2012-12-14,False,151315,48.89,3.168,223.719277,6.573,0,1,0,0,6602.134873,5514.078244,755.723167,3369.551255,5909.222727
7,1,1,2012-12-21,False,151315,56.02,3.098,223.839845,6.573,0,1,0,0,6542.819780,4891.878584,844.799071,3370.890041,6260.166622
8,1,1,2012-12-28,True,151315,44.79,3.108,223.960414,6.573,0,1,0,0,5522.283706,15477.095836,15506.919033,3207.440613,4415.666957
9,1,1,2013-01-04,False,151315,41.73,3.161,224.080983,6.525,0,1,0,0,6595.068146,6505.220540,809.934762,3491.044812,5819.351024
10,1,1,2013-01-11,False,151315,50.32,3.243,224.201552,6.525,0,1,0,0,6630.652457,4928.037995,591.603891,3209.555539,5662.793478
11,1,1,2013-01-18,False,151315,42.92,3.237,224.235813,6.525,0,1,0,0,6641.004112,5964.222985,651.827472,3340.764610,5572.918355
12,1,1,2013-01-25,False,151315,53.37,3.227,224.235552,6.525,0,1,0,0,6614.315215,4592.597197,602.546071,3186.528435,5764.305504
13,1,1,2013-02-01,False,151315,56.46,3.244,224.235290,6.525,0,1,0,0,6619.255743,4087.705560,548.877747,3106.930993,5751.392358
14,1,1,2013-02-08,True,151315,56.67,3.417,224.235029,6.525,0,1,0,0,5681.827862,12306.470808,14817.334501,2479.384791,3510.267551
15,1,1,2013-02-15,False,151315,49.66,3.475,224.276053,6.525,0,1,0,0,6780.799713,3862.859179,140.781114,2824.572155,4845.117229
16,1,1,2013-02-22,False,151315,50.25,3.597,224.420289,6.525,0,1,0,0,6857.517697,3174.627301,-103.396633,2605.865410,4429.460679
17,1,1,2013-03-01,False,151315,48.01,3.711,224.564526,6.525,0,1,0,0,6934.578766,2911.137286,-313.249320,2447.167494,3999.267270
18,1,1,2013-03-08,False,151315,50.81,3.658,224.708763,6.525,0,1,0,0,6894.493893,2793.156170,-229.149417,2490.314541,4226.198425
19,1,1,2013-03-15,False,151315,55.33,3.622,224.835681,6.525,0,1,0,0,6862.074203,2356.731674,-189.537155,2476.464082,4419.644294
20,1,1,2013-03-22,False,151315,63.42,3.611,224.919300,6.525,0,1,0,0,6838.980967,1310.577122,-222.048304,2361.891738,4579.387955
21,1,1,2013-03-29,False,151315,51.00,3.606,225.002920,6.525,0,1,0,0,6859.510047,3024.298289,-131.134983,2573.250266,4410.957032
22,1,1,2013-04-05,False,151315,58.59,3.583,225.086540,6.314,0,1,0,0,6763.755635,2038.210182,-152.171821,2466.744217,4569.938197
23,1,1,2013-04-12,False,151315,62.72,3.529,225.170160,6.314,0,1,0,0,6720.692689,1744.668270,-74.341507,2490.315903,4820.111037
24,1,1,2013-04-19,False,151315,67.10,3.451,225.170160,6.314,0,1,0,0,6662.049857,1537.059247,49.600657,2551.385674,5157.384587
25,1,1,2013-04-26,False,151315,59.23,3.417,225.170160,6.314,0,1,0,0,6655.447456,2776.716462,168.080539,2738.283456,5157.890073
26,1,1,2013-05-03,False,151315,66.66,3.386,176.000000,6.868,0,1,0,0,6991.674243,2395.810441,655.836428,3144.722243,5333.823867
27,1,1,2013-05-10,False,151315,63.90,3.392,176.000000,6.868,0,1,0,0,7000.883064,2741.362950,662.272643,3179.737816,5271.577519
28,1,1,2013-05-17,False,151315,69.53,3.454,176.000000,6.868,0,1,0,0,7029.831252,1667.050362,503.701387,2981.860758,5139.996195
29,1,1,2013-05-24,False,151315,77.19,3.494,176.000000,6.868,0,1,0,0,7040.698564,426.099223,374.850957,2788.185084,5115.448134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115034,45,98,2013-01-04,False,118221,32.87,3.592,192.659622,8.625,0,0,1,0,8094.621982,5274.935737,277.641140,3744.841869,5541.457796
115035,45,98,2013-01-11,False,118221,38.78,3.611,192.759980,8.625,0,0,1,0,8094.976898,4375.910761,200.576619,3614.756852,5564.105169
115036,45,98,2013-01-18,False,118221,41.45,3.605,192.809507,8.625,0,0,1,0,8085.743638,4042.299930,194.294682,3580.791878,5625.139541
115037,45,98,2013-01-25,False,118221,26.49,3.583,192.838701,8.625,0,0,1,0,8100.485514,6186.433935,335.735971,3863.202262,5477.711190
115038,45,98,2013-02-01,False,118221,34.92,3.615,192.867895,8.625,0,0,1,0,8104.599010,4880.382289,217.224686,3670.282670,5492.641410
115039,45,98,2013-02-08,True,118221,28.99,3.753,192.897089,8.625,0,0,1,0,7156.453353,14108.291143,14594.457160,3202.731090,3281.504578
115040,45,98,2013-02-15,False,118221,35.87,3.814,192.943471,8.625,0,0,1,0,8230.402793,3760.425262,-179.568457,3315.111214,4814.019030
115041,45,98,2013-02-22,False,118221,31.48,3.859,193.032822,8.625,0,0,1,0,8267.488420,4133.070927,-239.586042,3309.647954,4591.771821
115042,45,98,2013-03-01,False,118221,39.72,3.890,193.122173,8.625,0,0,1,0,8271.085698,2857.474690,-355.419058,3121.030101,4607.503883
115043,45,98,2013-03-08,False,118221,36.13,3.860,193.211524,8.625,0,0,1,0,8258.398238,3494.527646,-273.776419,3230.201507,4658.446929
115044,45,98,2013-03-15,False,118221,42.81,3.834,193.296277,8.625,0,0,1,0,8228.389732,2714.796278,-267.617871,3164.278049,4849.310222
115045,45,98,2013-03-22,False,118221,36.55,3.800,193.369533,8.625,0,0,1,0,8218.371637,3735.020493,-160.398514,3324.160743,4874.138267
115046,45,98,2013-03-29,False,118221,40.68,3.784,193.442790,8.625,0,0,1,0,8199.782824,3252.442269,-156.922384,3283.096430,4991.938825
115047,45,98,2013-04-05,False,118221,43.94,3.763,193.516047,8.335,0,0,1,0,8089.071819,2820.091462,-158.986874,3236.538785,5065.926136
115048,45,98,2013-04-12,False,118221,57.39,3.724,193.589304,8.335,0,0,1,0,8037.625400,1184.278232,-171.878384,3081.898997,5403.460538
115049,45,98,2013-04-19,False,118221,56.27,3.676,193.589304,8.335,0,0,1,0,8008.934727,1575.480615,-70.459512,3182.013001,5553.851886
115050,45,98,2013-04-26,False,118221,50.64,3.615,193.589304,8.335,0,0,1,0,7980.629499,2644.816911,86.152638,3378.186774,5681.950480
115051,45,98,2013-05-03,False,118221,56.07,3.592,176.000000,6.868,0,0,1,0,7567.681929,1656.822680,144.712478,3336.113822,5551.176841
115052,45,98,2013-05-10,False,118221,58.86,3.583,176.000000,6.868,0,0,1,0,7556.486063,1322.118499,143.955854,3305.716415,5624.320836
115053,45,98,2013-05-17,False,118221,60.59,3.614,176.000000,6.868,0,0,1,0,7573.063742,932.541963,71.821339,3224.560596,5542.274842
115054,45,98,2013-05-24,False,118221,67.11,3.627,176.000000,6.868,0,0,1,0,7568.781332,-18.988550,3.380376,3095.557742,5594.681160
115055,45,98,2013-05-31,False,118221,65.88,3.646,176.000000,6.868,0,0,1,0,7583.382296,53.764310,-25.735842,3083.354537,5510.081585
115056,45,98,2013-06-07,False,118221,70.71,3.633,176.000000,6.868,0,0,1,0,7565.659458,-538.511851,-32.101454,3026.335495,5627.719520
115057,45,98,2013-06-14,False,118221,70.01,3.632,176.000000,6.868,0,0,1,0,7566.373649,-438.322813,-25.528727,3039.511496,5620.714939
115058,45,98,2013-06-21,False,118221,70.13,3.626,176.000000,6.868,0,0,1,0,7562.283230,-424.787250,-14.564999,3047.764452,5643.409145
115059,45,98,2013-06-28,False,118221,76.05,3.639,176.000000,6.868,0,0,1,0,7559.164092,-1294.706836,-79.051428,2928.595354,5686.826338
115060,45,98,2013-07-05,False,118221,77.50,3.614,176.000000,6.868,0,0,1,0,7540.278830,-1367.525953,-39.630571,2947.412556,5795.618306
115061,45,98,2013-07-12,False,118221,79.37,3.614,176.000000,6.868,0,0,1,0,7536.653296,-1621.880005,-51.955531,2916.764015,5823.634408
115062,45,98,2013-07-19,False,118221,82.84,3.737,176.000000,6.868,0,0,1,0,7609.009874,-2705.947038,-315.795922,2650.388124,5447.245703
115063,45,98,2013-07-26,False,118221,76.06,3.804,176.000000,6.868,0,0,1,0,7665.233230,-2117.155108,-402.369792,2647.389509,5112.325691

In [ ]:
for i in range(0,115064):
    if (testdataset['MarkDown2'][i]==0.0):
        testdataset['MarkDown2'][i]=testdataset['cl2'][i]

In [232]:
testdataset['cl1']=predictions_MD1
testdataset['cl2']=predictions_MD2
testdataset['cl3']=predictions_MD3
testdataset['cl4']=predictions_MD4
testdataset['cl5']=predictions_MD5

In [234]:
testdataset

,Store,Dept,Date,IsHoliday,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,...,Unemployment,Weekly_Sales,Type_A,Type_B,Type_C,cl1,cl2,cl3,cl4,cl5
0,1,1,2012-11-02,False,151315,55.32,3.386,6766.44,5147.700000,50.82,...,6.573,0,1,0,0,6730.864162,3556.203113,288.531761,2895.048423,5245.614632
1,1,1,2012-11-09,False,151315,61.24,3.314,11421.32,3370.890000,40.28,...,6.573,0,1,0,0,6673.018940,3109.156083,390.405129,2920.499719,5585.114909
2,1,1,2012-11-16,False,151315,52.92,3.252,9696.28,292.100000,103.78,...,6.573,0,1,0,0,6649.159154,4549.166247,566.425807,3162.193933,5676.482029
3,1,1,2012-11-23,True,151315,56.23,3.211,883.59,4.170000,74910.32,...,6.573,0,1,0,0,5567.929414,13410.902839,15233.262569,2847.920373,4227.241032
4,1,1,2012-11-30,False,151315,52.34,3.207,2460.03,4851.395935,3838.35,...,6.573,0,1,0,0,6620.956493,4851.395935,657.539160,3247.507169,5824.785485
5,1,1,2012-12-07,False,151315,64.12,3.198,6343.16,3293.591060,270.00,...,6.573,0,1,0,0,6592.133956,3293.591060,597.095894,3069.347043,6032.751557
6,1,1,2012-12-14,False,151315,48.89,3.168,3504.83,5514.078244,73.26,...,6.573,0,1,0,0,6602.134873,5514.078244,755.723167,3369.551255,5909.222727
7,1,1,2012-12-21,False,151315,56.02,3.098,8231.71,4891.878584,274.00,...,6.573,0,1,0,0,6542.819780,4891.878584,844.799071,3370.890041,6260.166622
8,1,1,2012-12-28,True,151315,44.79,3.108,12659.55,37101.130000,174.78,...,6.573,0,1,0,0,5522.283706,15477.095836,15506.919033,3207.440613,4415.666957
9,1,1,2013-01-04,False,151315,41.73,3.161,1214.08,25366.330000,15.01,...,6.525,0,1,0,0,6595.068146,6505.220540,809.934762,3491.044812,5819.351024
10,1,1,2013-01-11,False,151315,50.32,3.243,6520.24,16134.600000,12.17,...,6.525,0,1,0,0,6630.652457,4928.037995,591.603891,3209.555539,5662.793478
11,1,1,2013-01-18,False,151315,42.92,3.237,3772.69,3559.460000,3.88,...,6.525,0,1,0,0,6641.004112,5964.222985,651.827472,3340.764610,5572.918355
12,1,1,2013-01-25,False,151315,53.37,3.227,965.89,1097.910000,0.10,...,6.525,0,1,0,0,6614.315215,4592.597197,602.546071,3186.528435,5764.305504
13,1,1,2013-02-01,False,151315,56.46,3.244,9290.91,1359.900000,265.00,...,6.525,0,1,0,0,6619.255743,4087.705560,548.877747,3106.930993,5751.392358
14,1,1,2013-02-08,True,151315,56.67,3.417,32355.16,729.800000,280.89,...,6.525,0,1,0,0,5681.827862,12306.470808,14817.334501,2479.384791,3510.267551
15,1,1,2013-02-15,False,151315,49.66,3.475,72937.29,6665.520000,47.21,...,6.525,0,1,0,0,6780.799713,3862.859179,140.781114,2824.572155,4845.117229
16,1,1,2013-02-22,False,151315,50.25,3.597,20107.75,3163.890000,42.20,...,6.525,0,1,0,0,6857.517697,3174.627301,-103.396633,2605.865410,4429.460679
17,1,1,2013-03-01,False,151315,48.01,3.711,10610.74,261.460000,2.80,...,6.525,0,1,0,0,6934.578766,2911.137286,-313.249320,2447.167494,3999.267270
18,1,1,2013-03-08,False,151315,50.81,3.658,5000.58,290.460000,78.77,...,6.525,0,1,0,0,6894.493893,2793.156170,-229.149417,2490.314541,4226.198425
19,1,1,2013-03-15,False,151315,55.33,3.622,3808.13,2356.731674,15.65,...,6.525,0,1,0,0,6862.074203,2356.731674,-189.537155,2476.464082,4419.644294
20,1,1,2013-03-22,False,151315,63.42,3.611,12553.98,1310.577122,495.10,...,6.525,0,1,0,0,6838.980967,1310.577122,-222.048304,2361.891738,4579.387955
21,1,1,2013-03-29,False,151315,51.00,3.606,13067.46,3024.298289,384.90,...,6.525,0,1,0,0,6859.510047,3024.298289,-131.134983,2573.250266,4410.957032
22,1,1,2013-04-05,False,151315,58.59,3.583,12872.34,5687.860000,485.97,...,6.314,0,1,0,0,6763.755635,2038.210182,-152.171821,2466.744217,4569.938197
23,1,1,2013-04-12,False,151315,62.72,3.529,3672.43,932.580000,52.86,...,6.314,0,1,0,0,6720.692689,1744.668270,-74.341507,2490.315903,4820.111037
24,1,1,2013-04-19,False,151315,67.10,3.451,3530.36,3.950000,107.50,...,6.314,0,1,0,0,6662.049857,1537.059247,49.600657,2551.385674,5157.384587
25,1,1,2013-04-26,False,151315,59.23,3.417,2387.72,2776.716462,98.34,...,6.314,0,1,0,0,6655.447456,2776.716462,168.080539,2738.283456,5157.890073
26,1,1,2013-05-03,False,151315,66.66,3.386,2298.63,2.000000,129.90,...,6.868,0,1,0,0,6991.674243,2395.810441,655.836428,3144.722243,5333.823867
27,1,1,2013-05-10,False,151315,63.90,3.392,4624.61,83.880000,42.38,...,6.868,0,1,0,0,7000.883064,2741.362950,662.272643,3179.737816,5271.577519
28,1,1,2013-05-17,False,151315,69.53,3.454,16170.50,92.000000,8.32,...,6.868,0,1,0,0,7029.831252,1667.050362,503.701387,2981.860758,5139.996195
29,1,1,2013-05-24,False,151315,77.19,3.494,7959.89,178.000000,1621.47,...,6.868,0,1,0,0,7040.698564,426.099223,374.850957,2788.185084,5115.448134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115034,45,98,2013-01-04,False,118221,32.87,3.592,1341.33,30325.140000,8.93,...,8.625,0,0,1,0,8094.621982,5274.935737,277.641140,3744.841869,5541.457796
115035,45,98,2013-01-11,False,118221,38.78,3.611,3877.36,15559.850000,3.81,...,8.625,0,0,1,0,8094.976898,4375.910761,200.576619,3614.756852,5564.105169
115036,45,98,2013-01-18,False,118221,41.45,3.605,14746.10,4071.060000,4.02,...,8.625,0,0,1,0,8085.743638,4042.299930,194.294682,3580.791878,5625.139541
115037,45,98,2013-01-25,False,118221,26.49,3.583,3130.28,1362.100000,0.20,...,8.625,0,0,1,0,8100.485514,6186.433935,335.735971,3863.202262,5477.711190
115038,45,98,2013-02-01,False,118221,34.92,3.615,14508.96,1092.530000,827.90,...,8.625,0,0,1,0,8104.599010,4880.382289,217.224686,3670.282670,5492.641410
115039,45,98,2013-02-08,True,118221,28.99,3.753,53311.88,531.330000,78.26,...,8.625,0,0,1,0,7156.453353,14108.291143,14594.457160,3202.731090,3281.504578
115040,45,98,2013-02-15,False,118221,35.87,3.814,9362.02,2017.680000,0.36,...,8.625,0,0,1,0,8230.402793,3760.425262,-179.568457,3315.111214,4814.019030
115041,45,98,2013-02-22,False,118221,31.48,3.859,10781.51,2735.670000,23.38,...,8.625,0,0,1,0,8267.488420,4133.070927,-239.586042,3309.647954,4591.771821
115042,45,98,2013-03-01,False,118221,39.72,3.890,6614.32,147.820000,5.60,...,8.625,0,0,1,0,8271.085698,2857.474690,-355.419058,3121.030101,4607.503883
115043,45,98,2013-03-08,False,118221,36.13,3.860,16382.54,88.670000,34.62,...,8.625,0,0,1,0,8258.398238,3494.527646,-273.776419,3230.201507,4658.446929
115044,45,98,2013-03-15,False,118221,42.81,3.834,9867.03,0.000000,11.08,...,8.625,0,0,1,0,8228.389732,2714.796278,-267.617871,3164.278049,4849.310222
115045,45,98,2013-03-22,False,118221,36.55,3.800,11923.74,0.000000,308.00,...,8.625,0,0,1,0,8218.371637,3735.020493,-160.398514,3324.160743,4874.138267
115046,45,98,2013-03-29,False,118221,40.68,3.784,5444.00,0.000000,350.84,...,8.625,0,0,1,0,8199.782824,3252.442269,-156.922384,3283.096430,4991.938825
115047,45,98,2013-04-05,False,118221,43.94,3.763,16427.83,5341.410000,182.59,...,8.335,0,0,1,0,8089.071819,2820.091462,-158.986874,3236.538785,5065.926136
115048,45,98,2013-04-12,False,118221,57.39,3.724,8760.15,1713.110000,21.08,...,8.335,0,0,1,0,8037.625400,1184.278232,-171.878384,3081.898997,5403.460538
115049,45,98,2013-04-19,False,118221,56.27,3.676,1399.81,39.890000,44.38,...,8.335,0,0,1,0,8008.934727,1575.480615,-70.459512,3182.013001,5553.851886
115050,45,98,2013-04-26,False,118221,50.64,3.615,1260.65,0.000000,57.52,...,8.335,0,0,1,0,7980.629499,2644.816911,86.152638,3378.186774,5681.950480
115051,45,98,2013-05-03,False,118221,56.07,3.592,8345.40,6.000000,92.96,...,6.868,0,0,1,0,7567.681929,1656.822680,144.712478,3336.113822,5551.176841
115052,45,98,2013-05-10,False,118221,58.86,3.583,4689.18,440.820000,53.09,...,6.868,0,0,1,0,7556.486063,1322.118499,143.955854,3305.716415,5624.320836
115053,45,98,2013-05-17,False,118221,60.59,3.614,4515.35,667.880000,6.12,...,6.868,0,0,1,0,7573.063742,932.541963,71.821339,3224.560596,5542.274842
115054,45,98,2013-05-24,False,118221,67.11,3.627,3249.34,481.820000,58.48,...,6.868,0,0,1,0,7568.781332,-18.988550,3.380376,3095.557742,5594.681160
115055,45,98,2013-05-31,False,118221,65.88,3.646,6474.49,411.380000,77.06,...,6.868,0,0,1,0,7583.382296,53.764310,-25.735842,3083.354537,5510.081585
115056,45,98,2013-06-07,False,118221,70.71,3.633,9977.82,744.290000,80.00,...,6.868,0,0,1,0,7565.659458,-538.511851,-32.101454,3026.335495,5627.719520
115057,45,98,2013-06-14,False,118221,70.01,3.632,2471.44,517.870000,348.54,...,6.868,0,0,1,0,7566.373649,-438.322813,-25.528727,3039.511496,5620.714939
115058,45,98,2013-06-21,False,118221,70.13,3.626,4989.34,385.310000,178.56,...,6.868,0,0,1,0,7562.283230,-424.787250,-14.564999,3047.764452,5643.409145
115059,45,98,2013-06-28,False,118221,76.05,3.639,4842.29,975.030000,3.00,...,6.868,0,0,1,0,7559.164092,-1294.706836,-79.051428,2928.595354,5686.826338
115060,45,98,2013-07-05,False,118221,77.50,3.614,9090.48,2268.580000,582.74,...,6.868,0,0,1,0,7540.278830,-1367.525953,-39.630571,2947.412556,5795.618306
115061,45,98,2013-07-12,False,118221,79.37,3.614,3789.94,1827.310000,85.72,...,6.868,0,0,1,0,7536.653296,-1621.880005,-51.955531,2916.764015,5823.634408
115062,45,98,2013-07-19,False,118221,82.84,3.737,2961.49,1047.070000,204.19,...,6.868,0,0,1,0,7609.009874,-2705.947038,-315.795922,2650.388124,5447.245703
115063,45,98,2013-07-26,False,118221,76.06,3.804,212.02,851.730000,2.06,...,6.868,0,0,1,0,7665.233230,-2117.155108,-402.369792,2647.389509,5112.325691

In [ ]:
testdataset['MarkDown1'].